version: "3.8"

services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: lara8fund-mailhog
    restart: unless-stopped
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web api
    networks:
      - lara8fund
